spring:
  #redis配置
  redis:
    host:
    pool:
    password:
    #连接超时时间
    timeout:
    #使用的分片
    database:
    #连接池配置
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0